### ISSUE TITLE
re-inventing the wheel 

### ISSUE THREAD

**Issue by Hotell** [ngParty/mockjay#1]
What do you want to achieve here @elmariofredo ?

We can use probably tools that already exist and work well.

checkout:
- https://github.com/typicode/json-server
- https://egghead.io/lessons/nodejs-creating-demo-apis-with-json-server

**Comment by devopsmariocom** [comment]
not for our special use cases ;)
- simple resource to json file mapping with json-server it's too much boilerplait in one file
- update resource without restarting server 
- REST exceptions ---> schema? :)
- multiple json setup files
- custom error responses

json server is nice when you have simple REST but with our special backend REST structure it's unusable, also it's already done I just want to move it to separate module ;)

**Comment by Hotell** [comment]
thank you for clarifying. all are valid points

yeah that's a shame that our backend team REST apis aren't REST apis. But pssst don't tell anyone ! :D

**Comment by devopsmariocom** [comment]
:sunglasses:
